extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://developers.google.com/style/word-list'
level: warning
ignorecase: false
action:
  name: replace
swap:
  'Postgres(?!QL)': PostgreSQL
  'cURL': curl
  'IPSec': IPsec
  'UNICODE': Unicode
  'No-SQL': NoSQL
  'No SQL': NoSQL
  'Oauth': OAuth 2.0
  'OAuth 2': OAuth 2.0
  'OAuth2': OAuth 2.0
  'WiFi': Wi-Fi
  'wifi': Wi-Fi
  'Wifi': Wi-Fi
  'HTTPs': HTTPS
  'https': HTTPS

